title:             Grace MOPS
email:             gracemopsop@gmail.com
description:       this is motherhood
author:            Grace MOPS
baseurl:           "/gracemops.github.io"
url:               "http://gracemops.github.io"

# Social Profiles
facebook_username: gracemopsorangepark

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
